version: "3"

services:
  webserver:
    # image: mattrayner/lamp:latest-1804
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: 'camagru_server'
    ports:
      - 80:80
      - 443:443
    volumes :
      - .:/app
      - ./logs:/var/log/apache2
